import React from 'react'
import Header from '../container/Header'
import Footer from '../container/Footer'
import { Container } from 'react-bootstrap'
import PlainContent from '../component/PlainContent'

export default () => {
    return (
        <div className="d-flex flex-column h-100">
            <main className="flex-shrink-0">
                <Header />
                <Container className="howto-section">
                    <PlainContent>
                        <h2><strong>SOLITAIRE100 PRIVACY NOTICE</strong></h2>
                        <p><strong>Last updated December 08, 2019</strong></p>
                        <p>Thank you for choosing to be part of our community at SOLITAIRE100 (“company”, “we”, “us”, or “our”). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about our policy, or our practices with regards to your personal information, please contact us at solitaire.100@outlook.com.</p>
                        <p>When you visit our website https://solitaire100.com, and use our services, you trust us with your personal information. We take your privacy very seriously. In this privacy notice, we describe our privacy policy. We seek to explain to you in the clearest way possible what information we collect, how we use it and what rights you have in relation to it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this privacy policy that you do not agree with, please discontinue use of our Sites and our services.</p>
                        <p>This privacy policy applies to all information collected through our website (such as https://solitaire100.com), and/or any related services, sales, marketing or events (we refer to them collectively in this privacy policy as the "<strong>Sites</strong>").</p>
                        <p><strong>Please read this privacy policy carefully.</strong></p>
                        <h5><strong>TABLE OF CONTENTS</strong></h5>
                        <p>1. WHAT INFORMATION DO WE COLLECT?<br /> 2. HOW DO WE USE YOUR INFORMATION?<br /> 3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?<br /> 4. WHO WILL YOUR INFORMATION BE SHARED WITH?<br /> 5. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?<br /> 6. WHAT IS OUR STANCE ON THIRD-PARTY WEBSITES?<br /> 7. HOW LONG DO WE KEEP YOUR INFORMATION?<br /> 8. HOW DO WE KEEP YOUR INFORMATION SAFE?<br /> 9. DO WE COLLECT INFORMATION FROM MINORS?<br /> 10. WHAT ARE YOUR PRIVACY RIGHTS?<br /> 11. CONTROLS FOR DO-NOT-TRACK FEATURES<br /> 12. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?<br /> 13. DO WE MAKE UPDATES TO THIS POLICY?<br /> 14. HOW CAN YOU CONTACT US ABOUT THIS POLICY?</p>
                        <h5><strong>1. WHAT INFORMATION DO WE COLLECT?</strong></h5>
                        <p><strong>Information automatically collected</strong></p>
                        <p><i><strong>In Short:</strong> Some information – such as IP address and/or browser and device characteristics – is collected automatically when you visit our Sites.</i></p>
                        <p>We automatically collect certain information when you visit, use or navigate the Sites. This information does not reveal your specific identity (like your name or contact information) but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, information about how and when you use our Sites and other technical information. This information is primarily needed to maintain the security and operation of our Sites, and for our internal analytics and reporting purposes.</p>
                        <p>Like many businesses, we also collect information through cookies and similar technologies.</p>
                        <p><strong>Information collected from other sources</strong></p>
                        <p><i><strong>In Short:</strong>  We may collect limited data from public databases, marketing partners, and other outside sources.</i></p>
                        <p>We may obtain information about you from other sources, such as public databases, joint marketing partners, as well as from other third parties. Examples of the information we receive from other sources include: social media profile information; marketing leads and search results and links, including paid listings (such as sponsored links).</p>
                        <h5><strong>2. HOW DO WE USE YOUR INFORMATION?</strong></h5>
                        <p><i><strong>In Short:</strong> We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent</i></p>
                        <p>We use personal information collected via our Sites for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests ("Business Purposes"), in order to enter into or perform a contract with you ("Contractual"), with your consent ("Consent"), and/or for compliance with our legal obligations ("Legal Reasons"). We indicate the specific processing grounds we rely on next to each purpose listed below. </p>
                        <p>We use the information we collect or receive:</p>
                        <p><strong>Deliver targeted advertising to you. </strong>We may use your information to develop and display content and advertising (and work with third parties who do so) tailored to your interests and/or location and to measure its effectiveness.</p>
                        <p><strong>For other Business Purposes.</strong>We may use your information for other Business Purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Sites, products, services, marketing and your experience. </p>
                        <h5><strong>3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?</strong></h5>
                        <p><i><strong>In Short:</strong>We only share information with your consent, to comply with laws, to protect your rights, or to fulfill business obligations.</i></p>
                        <p>We may process or share data based on the following legal basis:</p>
                        <ul>
                            <li><strong>Consent:</strong> We may process your data if you have given us specific consent to use your personal information in a specific purpose.</li>
                            <li><strong>Legitimate Interests:</strong> We may process your data when it is reasonably necessary to achieve our legitimate business interests.</li>
                            <li><strong>Performance of a Contract:</strong> Where we have entered into a contract with you, we may process your personal information to fulfill the terms of our contract.</li>
                            <li><strong>Legal Obligations:</strong> We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).</li>
                            <li><strong>Vital Interests:</strong> We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person and illegal activities, or as evidence in litigation in which we are involved.</li>
                        </ul>
                        <p>More specifically, we may need to process your data or share your personal information in the following situations: </p>
                        <ul>
                            <li><strong>Vendors, Consultants and Other Third-Party Service Providers.</strong>We may share your data with third party vendors, service providers, contractors or agents who perform services for us or on our behalf and require access to such information to do that work. Examples include: payment processing, data analysis, email delivery, hosting services, customer service and marketing efforts. We may allow selected third parties to use tracking technology on the Sites, which will enable them to collect data about how you interact with the Sites over time. This information may be used to, among other things, analyze and track data, determine the popularity of certain content and better understand online activity. Unless described in this Policy, we do not share, sell, rent or trade any of your information with third parties for their promotional purposes.</li>
                            <li><strong>Business Transfers.</strong> We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company. </li>
                        </ul>
                        <h5><strong>4. WHO WILL YOUR INFORMATION BE SHARED WITH?</strong></h5>
                        <p><i><strong>In Short:</strong>We only share information with the following third parties.</i></p>
                        <p>We only share and disclose your information with the following third parties. We have categorized each party so that you may be easily understand the purpose of our data collection and processing practices. If we have processed your data based on your consent and you wish to revoke your consent, please contact us. </p>
                        <ul>
                            <li><strong>Advertising, Direct Marketing, and Lead Generation</strong><br />Google AdSense</li>
                            <li><strong>Functionality and Infrastructure Optimisation</strong><br />Termly.io</li>
                            <li><strong>Web and Mobile Analytics</strong><br />Google Analytics</li>
                        </ul>
                        <h5><strong>5. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</strong></h5>
                        <p><i><strong>In Short:</strong> We may use cookies and other tracking technologies to collect and store your information.</i></p>
                        <p>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Policy.</p>
                        <h5><strong>6. WHAT IS OUR STANCE ON THIRD-PARTY WEBSITES?</strong></h5>
                        <p><i><strong>In Short:</strong>  We are not responsible for the safety of any information that you share with third-party providers who advertise, but are not affiliated with, our websites</i></p>
                        <p>The Sites may contain advertisements from third parties that are not affiliated with us and which may link to other websites, online services or mobile applications. We cannot guarantee the safety and privacy of data you provide to any third parties. Any data collected by third parties is not covered by this privacy policy. We are not responsible for the content or privacy and security practices and policies of any third parties, including other websites, services or applications that may be linked to or from the Sites. You should review the policies of such third parties and contact them directly to respond to your questions.</p>
                        <h5><strong>7. HOW LONG DO WE KEEP YOUR INFORMATION?</strong></h5>
                        <p><i><strong>In Short:</strong>  We keep your information for as long as necessary to fulfill the purposes outlined in this privacy policy unless otherwise required by law</i></p>
                        <p>We will only keep your personal information for as long as it is necessary for the purposes set out in this privacy policy, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements).</p>
                        <p>When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize it, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</p>
                        <h5><strong>8. HOW DO WE KEEP YOUR INFORMATION SAFE?</strong></h5>
                        <p><i><strong>In Short:</strong> We aim to protect your personal information through a system of organisational and technical security measures</i></p>
                        <p>We have implemented appropriate technical and organisational security measures designed to protect the security of any personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your personal information, transmission of personal information to and from our Sites is at your own risk. You should only access the services within a secure environment.</p>
                        <h5><strong>9. DO WE COLLECT INFORMATION FROM MINORS?</strong></h5>
                        <p><i><strong>In Short:</strong>  We do not knowingly collect data from or market to children under 13 years of age.</i></p>
                        <p>We do not knowingly solicit data from or market to children under 13 years of age. By using the Sites, you represent that you are at least 13 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the Sites. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we have collected from children under age 13, please contact us at solitaire.100@outlook.com</p>
                        <h5><strong>10. WHAT ARE YOUR PRIVACY RIGHTS?</strong></h5>
                        <p><i><strong>In Shirt:</strong>  In some regions, such as the European Economic Area, you have rights that allow you greater access to and control over your personal information. You may review, change, or terminate your account at any time</i></p>
                        <p>In some regions (like the European Economic Area), you have certain rights under applicable data protection laws. These may include the right (i) to request access and obtain a copy of your personal information, (ii) to request rectification or erasure; (iii) to restrict the processing of your personal information; and (iv) if applicable, to data portability. In certain circumstances, you may also have the right to object to the processing of your personal information. To make such a request, please use the contact details provided below. We will consider and act upon any request in accordance with applicable data protection laws.</p>
                        <p>If we are relying on your consent to process your personal information, you have the right to withdraw your consent at any time. Please note however that this will not affect the lawfulness of the processing before its withdrawal.</p>
                        <p>If you are resident in the European Economic Area and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here: http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm.</p>
                        <p><strong>Cookies and similar technologies:</strong> Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our Sites.</p>
                        <h5><strong>11. CONTROLS FOR DO-NOT-TRACK FEATURES</strong></h5>
                        <p>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (“DNT”) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. No uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this Privacy Policy.</p>
                        <h5><strong>12. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?</strong></h5>
                        <p><i><strong>In Short:</strong> Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information</i></p>
                        <p>California Civil Code Section 1798.83, also known as the “Shine The Light” law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.</p>
                        <p>If you are under 18 years of age, reside in California, and have a registered account with the Sites, you have the right to request removal of unwanted data that you publicly post on the Sites. To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the Sites, but please be aware that the data may not be completely or comprehensively removed from our systems.</p>
                        <h5><strong>13. DO WE MAKE UPDATES TO THIS POLICY?</strong></h5>
                        <p><i><strong>In Short:</strong> Yes, we will update this policy as necessary to stay compliant with relevant laws.</i></p>
                        <p>We may update this privacy policy from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this privacy policy, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this privacy policy frequently to be informed of how we are protecting your information.</p>
                        <h5><strong>14. HOW CAN YOU CONTACT US ABOUT THIS POLICY?</strong></h5>
                        <p>If you have questions or comments about this policy, you may contact us by email at solitaire.100@outlook.com.</p>
                        <p><i>Based on the laws of some countries, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances.</i></p>
                    </PlainContent>
                </Container>
            </main>
            <Footer />
        </div>
    )
}